[package]
name = "e_140w_p_passwd"
version = "0.1.0"
authors = ["Jiasheng Shi <jiasheng@live.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.13"
lzw = "0.10.0"
quick-xml = "0.14.0"

[profile.release]
opt-level = 3